TH_Lab04/Models/Course.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TH_Lab04.Models
{
    public class Course
    {
        public Course()
        {
            Enrollments = new HashSet<Enrollment>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

TH_Lab04/Models/Enrollment.cs
namespace TH_Lab04.Models
{
    public class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public int LearnerID { get; set; }

        public float Grade { get; set; }
        public virtual Learner? Learner { get; set; }
        public virtual Course? Course { get; set; }
    }
}

TH_Lab04/Models/ErrorViewModel.cs
namespace TH_Lab04.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TH_Lab04/Models/Learner.cs
namespace TH_Lab04.Models
{
    public class Learner
    {
        public Learner()
        {
            Enrollments = new HashSet<Enrollment>();
        }
        public int LearnerID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int MajorID { get; set; }
        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

TH_Lab04/Models/Major.cs
namespace TH_Lab04.Models
{
    public class Major
    {
        public Major()
        {
            Learners = new HashSet<Learner>();
        }
        public int MajorID { get; set; }
        public string MajorName { get; set; }
        public virtual ICollection<Learner> Learners { get; set; }
    }
}

TH_Lab04/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TH_Lab04.Models;

namespace TH_Lab04.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TH_Lab04/Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TH_Lab04.Data;
using TH_Lab04.Models;
using TH_Lab04.Data;
using TH_Lab04.Models;

namespace MyWebApp.Controllers
{
    public class LearnerController : Controller
    {
        private readonly SchoolContext db;

        public LearnerController(SchoolContext context)
        {
            db = context;
        }

        // GET: /Learner/Index
        public IActionResult Index(int? id)
        {
            IQueryable<Learner> learners = db.Learners.Include(m => m.Major);
            if (id != null)
            {
                learners = learners.Where(l => l.MajorID == id);
            }
            return View(learners.ToList());
        }

        // GET: /Learner/LearnerByMajorID
        public IActionResult LearnerByMajorID(int mid)
        {
            var learners = db.Learners.Where(l => l.MajorID == mid).Include(m => m.Major).ToList();

            return PartialView("LearnerTable", learners);
        }

        public IActionResult Create()
        {
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstMidName, LastName, MajorID, EnrollmentDate")] Learner learner)
        {
            if (ModelState.IsValid)
            {
                db.Learners.Add(learner);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
            return View(learner);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();
            var learner = db.Learners.Find(id);
            if (learner == null) return NotFound();
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
            return View(learner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("LearnerID,FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
        {
            if (id != learner.LearnerID) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(learner);
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!db.Learners.Any(e => e.LearnerID == id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName", learner.MajorID);
            return View(learner);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound();
            var learner = db.Learners.Include(l => l.Major).Include(l => l.Enrollments)
                .FirstOrDefault(m => m.LearnerID == id);
            if (learner == null) return NotFound();
            if (learner.Enrollments.Any()) return Content("This learner has enrollments, cannot delete!");
            return View(learner);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var learner = db.Learners.Find(id);
            if (learner != null) db.Learners.Remove(learner);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

TH_Lab04/ViewComponents/MajorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TH_Lab04.Data;
using System.Linq; 

namespace MyWebApp.ViewComponents
{
    public class MajorViewComponent : ViewComponent
    {
        private readonly SchoolContext db;

        public MajorViewComponent(SchoolContext context)
        {
            db = context;
        }
        public IViewComponentResult Invoke()
        {
            var majors = db.Majors.ToList();
            return View(majors);
        }
    }
}

TH_Lab04/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TH_Lab04/Views/Learner/Create.cshtml
@using TH_Lab04.Models
@model Learner

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ms-2 mx-2">
    <h1>Create Learner</h1>
    <hr />

    <form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group row mb-2">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="Tên Đệm và Tên">
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Họ">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="MajorID" class="col-sm-2 col-form-label">Ngành học</label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="form-control"
                        asp-items="@ViewBag.MajorID">
                    <option value="">-- Chọn Ngành --</option>
                </select>
                <span asp-validation-for="MajorID" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control" type="date">
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row" style="margin-top:10px">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </div>
    </form>
</div>

TH_Lab04/Views/Learner/Delete.cshtml
@using TH_Lab04.Models
@model Learner

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ms-2 mx-2">
    <h1>Delete Confirmation</h1>
    <h3 class="text-danger">Bạn có chắc chắn muốn xóa học viên này không?</h3>
    <hr />

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            Ngành (Major)
        </dt>
        <dd class="col-sm-10">
            @(Model.Major?.MajorName ?? "N/A")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="LearnerID" />
        <input type="submit" value="Confirm Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

TH_Lab04/Views/Learner/Edit.cshtml
@using TH_Lab04.Models
@model Learner

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ms-2 mx-2">
    <h1>Edit Learner</h1>
    <hr />

    <form asp-controller="Learner" asp-action="Edit" method="post" class="mt-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="LearnerID" />

        <div class="form-group row mb-2">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control">
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="MajorID" class="col-sm-2 col-form-label">Ngành học</label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="form-control"
                        asp-items="@ViewBag.MajorID">
                </select>
                <span asp-validation-for="MajorID" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control" type="date">
                <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row" style="margin-top:10px">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </div>
    </form>
</div>

TH_Lab04/Views/Learner/Index.cshtml
@using TH_Lab04.Models
@model IEnumerable<Learner>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        <h3>Majors</h3>
        @await Component.InvokeAsync("Major")
    </div>

    <div class="col-md-9">
        <h1>Learner List</h1>
        <a asp-action="Create" class="btn btn-primary mb-3">Create New Learner</a>
        <div id="content">
            @await Html.PartialAsync("LearnerTable", Model)
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>
        $(document).ready(function() {
            $("li.list-group-item-action").click(function (e) {
                var id = $(this).attr("id");
                if (id && !isNaN(id)) {
                    $.ajax({
                        url: "/Learner/LearnerByMajorID",
                        type: "GET", 
                        data: { mid: id }, 
                        success: function (response) {
                            $("#content").html(response); 
                        },
                        error: function(xhr, status, error) {
                            console.error("AJAX Error: ", status, error);
                        }
                    });
                }
            });
        });
    </script>
}

TH_Lab04/Views/Learner/LearnerTable.cshtml
@using TH_Lab04.Models
@model IEnumerable<Learner>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.LearnerID)</th>
            <th>@Html.DisplayNameFor(model => model.FirstMidName)</th>
            <th>@Html.DisplayNameFor(model => model.LastName)</th>
            <th>Ngành (Major)</th>
            <th>@Html.DisplayNameFor(model => model.EnrollmentDate)</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@(s.Major?.MajorName ?? "N/A")</td>
                <td>@s.EnrollmentDate.ToShortDateString()</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@s.LearnerID" class="btn btn-sm btn-info">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@s.LearnerID" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TH_Lab04/Views/Shared/Components/Major/Default.cshtml
@using TH_Lab04.Models
@model IEnumerable<Major>

@{
    Layout = null;
}

<div class="list-group">
    <a asp-action="Index" asp-controller="Learner" class="list-group-item list-group-item-action">
        All Majors
    </a>

    @foreach (var m in Model)
    {
        <li class="list-group-item list-group-item-action" id="@m.MajorID">
            @m.MajorName
        </li>
    }
</div>

TH_Lab04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TH_Lab04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TH_Lab04.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TH_Lab04</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TH_Lab04 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>